---
title: "Figure 4 Metzincin protease paper"
author: "Jasmin Wächter"
date: "2/9/2022"
output: html_document
---

```{r}

setwd("/Volumes/FREECOM HDD/R_ADAM")


library(ape)
library(DoubletFinder)
library(remotes)
library(Matrix)
library(fields)
library(KernSmooth)
library(ROCR)
library(parallel)
library(SingleCellExperiment)
library(Seurat)
library(tidyverse)
library(Matrix)
library(scales)
library(cowplot)
library(RCurl)
library(dplyr)
library(stringr)
library(ggplot2)
library(fields)
library(clustree)
library(ggraph)
library(plotly)
library(MAST)
library(multtest)
library(metap)

library(SeuratWrappers)
library(VGAM)
library(patchwork)
library(RColorBrewer)
library(plotly)



#Load the trophoblast object generated by Matthew Shannon
load("/Volumes/FREECOM HDD/R_ADAM/Trophoblast.Rdata")

```

#Add clustern names independently
```{r}
Trophoblasts@meta.data$cluster_name<- NA

Trophoblasts@meta.data$cluster_name[which(stringr::str_detect(Trophoblasts@meta.data$seurat_clusters, "^0"))] <- "CTB 1"
Trophoblasts@meta.data$cluster_name[which(stringr::str_detect(Trophoblasts@meta.data$seurat_clusters, "^1"))] <- "CTB 2"
Trophoblasts@meta.data$cluster_name[which(stringr::str_detect(Trophoblasts@meta.data$seurat_clusters, "^2"))] <- "CTB 3"
Trophoblasts@meta.data$cluster_name[which(stringr::str_detect(Trophoblasts@meta.data$seurat_clusters, "^3"))] <- "CTB 4"
Trophoblasts@meta.data$cluster_name[which(stringr::str_detect(Trophoblasts@meta.data$CellType, "^4"))] <- "cCTB 1"
Trophoblasts@meta.data$cluster_name[which(stringr::str_detect(Trophoblasts@meta.data$seurat_clusters, "^7"))] <- "cCTB 2"
Trophoblasts@meta.data$cluster_name[which(stringr::str_detect(Trophoblasts@meta.data$seurat_clusters, "^5"))] <- "EVT"
Trophoblasts@meta.data$cluster_name[which(stringr::str_detect(Trophoblasts@meta.data$seurat_clusters, "^6"))] <- "SCTp"

```

#Reorder clusters
```{r}
Idents(Trophoblasts) <- "cluster_name"
#this is to have the clusters appear in the order that you desire
my_levels <- c("SCTp", "CTB 1","CTB 2", "CTB 3", "CTB 4", "cCTB 1","cCTB 2", "EVT")

# Re-level object@ident
Trophoblasts@active.ident <- factor(x = Trophoblasts@active.ident, levels = my_levels)
#View(Trophoblasts@meta.data)

```

#Velocity arrows have been generated as described by Matthew Shannon in Shannon et al., 2021


#4B-C-D
```{r}
Idents(Trophoblasts) <- "cluster_name"
DefaultAssay (object = Trophoblasts) <- "RNA"

#MMP15
pdf("Violin_MMP15.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("MMP15"), pt.size = 0)+NoLegend()
dev.off()

jpeg("Feature_MMP15.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("MMP15"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()

#TLL1
pdf("Violin_TLL1.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("TLL1"), pt.size = 0)+NoLegend()
dev.off()


jpeg("Feature_TLL1.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("TLL1"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()

#MMP23B
pdf("Violin_MMP23B.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("MMP23B"), pt.size = 0)+NoLegend()
dev.off()

jpeg("Feature_MMP23B.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("MMP23B"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()
```




#3B-C-D continued
```{r}
#ADAM10
jpeg("Feature_ADAM10.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("ADAM10"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()

pdf("Violin_ADAM10.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("ADAM10"), pt.size = 0)+NoLegend()
dev.off()

#TLL2
jpeg("Feature_TLL2.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("TLL2"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()

pdf("Violin_TLL2.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("TLL2"), pt.size = 0)+NoLegend()
dev.off()

#MMP14
pdf("Violin_MMP14.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("MMP14"), pt.size = 0)+NoLegend()
dev.off()

jpeg("Feature_MMP14.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("MMP14"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()

#MMP19
pdf("Violin_MMP19.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("MMP19"), pt.size = 0)+NoLegend()
dev.off()

jpeg("Feature_MMP19.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("MMP19"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()

#ADAMTS1
pdf("Violin_ADAMTS1.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("ADAMTS1"), pt.size = 0)+NoLegend()
dev.off()

jpeg("Feature_ADAMTS1.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("ADAMTS1"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()

#ADAMTS6
pdf("Violin_ADAMTS6_org.pdf",  width=6, height=5)
VlnPlot  (object = interface.integrated, features = c("ADAMTS6"), pt.size = 0)+NoLegend()
dev.off()

jpeg("Feature_ADAMTS6.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = interface.integrated, features = c("ADAMTS6"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()
```


#Trophoblast markers
```{r}
#CDX2
jpeg("Feature_CDX2.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("CDX2"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()

pdf("Violin_CDX2.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("CDX2"), pt.size = 0)+NoLegend()
dev.off()

#TEAD4
pdf("Violin_TEAD4.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("TEAD4"), pt.size = 0)+NoLegend()
dev.off()

jpeg("Feature_TEAD4.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("TEAD4"),  sort.cell = TRUE, pt.size = 1,   min.cutoff = 0, order = TRUE, cols = c("grey", "red"))+NoLegend()+ theme(axis.line = element_blank(),axis.title=element_blank(),axis.text = element_blank(),axis.ticks = element_blank())
dev.off()

#MKI67
jpeg("MKI67_interface.jpeg", units="in", width=6, height=5, res=300)
FeaturePlot  (object = Trophoblasts, features = c("MKI67"),     min.cutoff = 0, order = TRUE, cols = c("grey", "red") , pt.size = 1                 )+ NoLegend()
dev.off()

pdf("Violin_MKI67.pdf",  width=6, height=5)
VlnPlot  (object = Trophoblasts, features = c("MKI67"), pt.size = 0)+NoLegend()
dev.off()
```

